/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadulpgrupo50.Vistas;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.LocalDate;
import java.util.Date;

import javax.swing.JOptionPane;
import universidadulpgrupo50.AccesoADatos.AlumnoData;
import universidadulpgrupo50.Entidades.Alumno;

/**
 *
 * @author Carina
 */
public class GestionDeAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionDeAlumnos
     */
    public GestionDeAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabeldocum = new javax.swing.JLabel();
        jLabelapell = new javax.swing.JLabel();
        jLabelnomb = new javax.swing.JLabel();
        jLabelesta = new javax.swing.JLabel();
        jLabelfechana = new javax.swing.JLabel();
        jTextFieldoc = new javax.swing.JTextField();
        jTapellido = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jRestado = new javax.swing.JRadioButton();
        jDatefechaNa = new com.toedter.calendar.JDateChooser();
        jBbuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Alumno");

        jLabeldocum.setText("Documento");

        jLabelapell.setText("Apellido");

        jLabelnomb.setText("Nombre");

        jLabelesta.setText("Estado");

        jLabelfechana.setText("Fecha de Nacimiento");

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelnomb)
                                .addGap(72, 72, 72)
                                .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelesta)
                                .addGap(61, 61, 61)
                                .addComponent(jRestado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelapell)
                                    .addComponent(jLabeldocum))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldoc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBbuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelfechana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDatefechaNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jBModificar)
                .addGap(18, 18, 18)
                .addComponent(jBeliminar)
                .addGap(18, 18, 18)
                .addComponent(jBguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsalir)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeldocum)
                            .addComponent(jTextFieldoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBbuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelapell)
                            .addComponent(jTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnomb)
                            .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelesta))
                    .addComponent(jRestado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelfechana)
                    .addComponent(jDatefechaNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModificar)
                    .addComponent(jBeliminar)
                    .addComponent(jBguardar)
                    .addComponent(jBsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    AlumnoData Data1 = new AlumnoData();
    
    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed

        try {
            int dni = Integer.parseInt(jTextFieldoc.getText());
            if (Data1.buscarAlumnoPorDni(dni) != null) {

                Alumno alumno = Data1.buscarAlumnoPorDni(dni);
                jTnombre.setText(alumno.getNombre());
                jTapellido.setText(alumno.getApellido());
                jRestado.setSelected(alumno.isEstado());
                jDatefechaNa.setDate(java.sql.Date.valueOf(alumno.getFechaNacimiento()));

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Caracter inválido  " + e);
        }


    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
      this.dispose(); 
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
      // int dni = Integer.parseInt(jTextFieldoc.getText());
        int dni = Integer.parseInt(jTextFieldoc.getText());
            Alumno alumnoRecuperado = Data1.buscarAlumnoPorDni(dni);       
      if (alumnoRecuperado != null) {
                Alumno alumno2 = new Alumno(alumnoRecuperado.getIdAlumno() ,
                        Integer.parseInt(jTextFieldoc.getText()), 
                        jTnombre.getText(), jTapellido.getText(), 
                        jDatefechaNa.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), 
                        jRestado.isSelected());
                Data1.modificarAlumno(alumno2);
      }  else {
                  JOptionPane.showMessageDialog(null, "No se encontró el alumno con DNI: " + dni);

      }
      
        
        
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed

        try {
            int dni = Integer.parseInt(jTextFieldoc.getText());
            LocalDate fecha = jDatefechaNa.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Alumno alumno1 = new Alumno(dni, jTnombre.getText(), jTapellido.getText(), fecha, jRestado.isSelected());
            Data1.guardarAlumno(alumno1);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, " Error, los datos ingresados son invalidos  " + e);
        }


    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
       
       try {
            int dni = Integer.parseInt(jTextFieldoc.getText());
        if (Data1.buscarAlumnoPorDni(dni)!=null){
            Data1.eliminarAlumno(dni);
                      
        }
                jTextFieldoc.setText("");
                jTnombre.setText("");
                jTapellido.setText("");
                jRestado.setSelected(false);
                jDatefechaNa.setDate(null);
        
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Error al eliminar. Por favor, corrobore el DNI e intente de nuevo  " + e);
       }
       
    }//GEN-LAST:event_jBeliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBsalir;
    private com.toedter.calendar.JDateChooser jDatefechaNa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelapell;
    private javax.swing.JLabel jLabeldocum;
    private javax.swing.JLabel jLabelesta;
    private javax.swing.JLabel jLabelfechana;
    private javax.swing.JLabel jLabelnomb;
    private javax.swing.JRadioButton jRestado;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTextFieldoc;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables
}
