/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadulpgrupo50.Vistas;

/**
 *
 * @author Carina
 */
public class vistasMenu extends javax.swing.JFrame {

    /**
     * Creates new form vistasMenu
     */
    public vistasMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenualumno = new javax.swing.JMenu();
        jMitemAlumno = new javax.swing.JMenuItem();
        jMenumateria = new javax.swing.JMenu();
        jMenuItemformmat = new javax.swing.JMenuItem();
        jMenuadmin = new javax.swing.JMenu();
        jMenuItemmanejoins = new javax.swing.JMenuItem();
        jMenuItemmanipnota = new javax.swing.JMenuItem();
        jMenuconsul = new javax.swing.JMenu();
        jMenuItemalumxmateria = new javax.swing.JMenuItem();
        jMenusalir = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenualumno.setText("Alumno");
        jMenualumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenualumnoActionPerformed(evt);
            }
        });

        jMitemAlumno.setText("Formulario de Alumno");
        jMitemAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMitemAlumnoActionPerformed(evt);
            }
        });
        jMenualumno.add(jMitemAlumno);

        jMenuBar1.add(jMenualumno);

        jMenumateria.setText("Materia");

        jMenuItemformmat.setText("Formulario de Materia");
        jMenumateria.add(jMenuItemformmat);

        jMenuBar1.add(jMenumateria);

        jMenuadmin.setText("Administracion");

        jMenuItemmanejoins.setText("Manejo de Inscripciones");
        jMenuadmin.add(jMenuItemmanejoins);

        jMenuItemmanipnota.setText("Manipulacion de Nota");
        jMenuItemmanipnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemmanipnotaActionPerformed(evt);
            }
        });
        jMenuadmin.add(jMenuItemmanipnota);

        jMenuBar1.add(jMenuadmin);

        jMenuconsul.setText("Consultas");

        jMenuItemalumxmateria.setText("Alumnos por Materia");
        jMenuconsul.add(jMenuItemalumxmateria);

        jMenuBar1.add(jMenuconsul);

        jMenusalir.setText("Salir");
        jMenuBar1.add(jMenusalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemmanipnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemmanipnotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemmanipnotaActionPerformed

    private void jMitemAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMitemAlumnoActionPerformed
        
        
    }//GEN-LAST:event_jMitemAlumnoActionPerformed

    private void jMenualumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenualumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenualumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistasMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemalumxmateria;
    private javax.swing.JMenuItem jMenuItemformmat;
    private javax.swing.JMenuItem jMenuItemmanejoins;
    private javax.swing.JMenuItem jMenuItemmanipnota;
    private javax.swing.JMenu jMenuadmin;
    private javax.swing.JMenu jMenualumno;
    private javax.swing.JMenu jMenuconsul;
    private javax.swing.JMenu jMenumateria;
    private javax.swing.JMenu jMenusalir;
    private javax.swing.JMenuItem jMitemAlumno;
    // End of variables declaration//GEN-END:variables
}
